name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Run Tests & Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for semantic-release

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt  # Install dev dependencies
          pip install pre-commit pytest python-semantic-release  # Required tools

      - name: Run Pre-commit Checks
        run: pre-commit run --all-files

      - name: Run Pytest
        run: pytest tests/ --disable-warnings  # Adjust test folder as needed

  release:
    name: Release with Semantic Versioning
    runs-on: ubuntu-latest
    needs: ci  # Only run after tests pass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for semantic-release

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Semantic Release
        run: pip install python-semantic-release

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version
          semantic-release publish
