name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"  # Runs when a Git tag like v0.3.0 is pushed

jobs:
  ci:
    name: Run Tests & Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Poetry & Dependencies
        run: |
          pip install poetry
          poetry install --no-interaction --no-root

      - name: Run Pre-commit Checks
        run: poetry run pre-commit run --all-files

      - name: Run Pytest
        run: poetry run pytest tests/ --disable-warnings

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: ci  # Ensures tests pass before releasing
    if: startsWith(github.ref, 'refs/tags/v')  # Only runs on version tags

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Build Package
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}  # Store this in GitHub Secrets
        run: poetry publish --username __token__ --password $POETRY_PYPI_TOKEN

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
