on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  build:
    name: 👋 Welcome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "🚀 Hey there, awesome human(hopefully :P)! Thanks for opening an issue! 🙌 The team has been notified and will get back to you ASAP. Stay tuned! 🔧"
          pr-message: "🔥 Boom! A new PR has landed! 🚀 Thanks for contributing! The team is on it and will review it soon. Stay awesome! ✨"
